<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="csm" nsURI="http://eu.cloudscaleproject.env/CloudscaleComponentModel/1.0"
    nsPrefix="csm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package is the root package of all packages of the CloudScale Model (CSM)."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Csm">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The CSM is the single root element of the XMI file which is generated for the CSM model. It consist of two main sub-models; Architecture and SystemDefinition."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="architecture" eType="#//architecture/Architecture"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//definition/SystemDefinition"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="core" nsURI="http://eu.cloudscaleproject.env/CloudscaleComponentModel/Core/1.0"
      nsPrefix="core">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This package contains several core classes that are used by classes from other two packages (i.e. Architecture and Definition package). It provides abstract base class Entity, used by all other classes, providing them id, name and description attributes. Additionally, the package provides business logic related classes; modules, operation interfaces and operations. "/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="AVEntry" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AEEntry" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Entity is a meta-class high up the CSM meta-class hierarchy and represents all entities of the CSM that have an id, name and description. Additionally the Entity contains key-value set, which can be used to extend the model with additional information.&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="" unsettable="true" iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="avMap" upperBound="-1"
          eType="#//core/AVEntry" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aeMap" upperBound="-1"
          eType="#//core/AEEntry" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operation represents specific operation signature in association to parameters and return value.&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnValue" eType="#//core/TypeEnum">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
          eType="#//core/TypeEnum">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TypeEnum">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This entity represents a data type that can be used for specification and modeling of interface operation signatures.&#xA;"/>
      </eAnnotations>
      <eLiterals name="INT"/>
      <eLiterals name="STRING" value="1"/>
      <eLiterals name="BOOL" value="2" literal="BOOL"/>
      <eLiterals name="DOUBLE" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationInterface" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This entity models represents provided or required services, used by modules (see Module), as a set of operation signatures (see Operation). "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//core/Operation" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providingContainer" eType="#//architecture/OperationInterfaceContainer"
          eOpposite="#//architecture/OperationInterfaceContainer/providedInterfaces">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiringContainer" upperBound="-1"
          eType="#//architecture/OperationInterfaceContainer" eOpposite="#//architecture/OperationInterfaceContainer/requiredInterfaces"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="architecture" nsURI="http://eu.cloudscaleproject.env/CloudscaleComponentModel/Architecture/1.0"
      nsPrefix="architecture">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The package contains base classes for building cloud based systems. The classes are abstract representation of the cloud system architecture, while the exact specification is referenced through descriptors defined in the Definition package."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Architecture" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Architecture view provides a descriptive abstraction of the system’s architecture, without any additional performance or cost information. The root entity of the system architecture is the cloud provider (see CloudProvider), defining an abstract cloud environment that consists of components (see Component), defining provided services, and connections (see Connection) between them, defining requested intererfaces.&#xA;Additionally, for the purpose of connectivity with the external environment, connectors (see Connector) are introduced into the model that can function as an operation provider or as an operation requester.&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudProviders" upperBound="-1"
          eType="#//architecture/CloudEnvironment" containment="true" eOpposite="#//architecture/CloudEnvironment/architecture">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="proxies" upperBound="-1"
          eType="#//architecture/Proxy" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalConnections"
          upperBound="-1" eType="#//architecture/ExternalConnection" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hybridConnections" upperBound="-1"
          eType="#//architecture/HybridConnection" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unresolvedOperationInterfaces"
          upperBound="-1" eType="#//core/OperationInterface" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloudEnvironment" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The CloudProvider model represents abstract cloud environment. It consists of components, the deployment information of node components (for IaaS clouds) and internal connections between the components (see InternalConnection). &#xA;The nature of the cloud (IaaS and PaaS) are specified through the cloud provider descriptor (see CloudProviderDescriptor)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalConnections"
          upperBound="-1" eType="#//architecture/InternalConnection" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudProviderDescriptor"
          lowerBound="1" eType="#//definition/CloudEnvironmentDescriptor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="availabilityZoneDescriptor"
          eType="#//definition/AvailabilityZoneDescriptor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="architecture" eType="#//architecture/Architecture"
          eOpposite="#//architecture/Architecture/cloudProviders">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructureLayer"
          lowerBound="1" eType="#//architecture/InfrastructureLayer" containment="true"
          eOpposite="#//architecture/InfrastructureLayer/cloudProvider">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platformLayer" lowerBound="1"
          eType="#//architecture/PlatformLayer" containment="true" eOpposite="#//architecture/PlatformLayer/cloudEnvironment">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="softwareLayer" lowerBound="1"
          eType="#//architecture/SoftwareLayer" containment="true" eOpposite="#//architecture/SoftwareLayer/cloudProvider">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InfrastructureLayer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
          eType="#//architecture/InfrastructureService" containment="true" eOpposite="#//architecture/InfrastructureService/infrastructureLayer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudProvider" lowerBound="1"
          eType="#//architecture/CloudEnvironment" eOpposite="#//architecture/CloudEnvironment/infrastructureLayer">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PlatformLayer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
          eType="#//architecture/PlatformService" containment="true" eOpposite="#//architecture/PlatformService/platformLayer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudEnvironment" lowerBound="1"
          eType="#//architecture/CloudEnvironment" eOpposite="#//architecture/CloudEnvironment/platformLayer">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareLayer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
          eType="#//architecture/SoftwareService" containment="true" eOpposite="#//architecture/SoftwareService/softwareLayer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudProvider" lowerBound="1"
          eType="#//architecture/CloudEnvironment" eOpposite="#//architecture/CloudEnvironment/softwareLayer">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true" eSuperTypes="#//core/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="InfrastructureService" abstract="true"
        eSuperTypes="#//architecture/Service">
      <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructureLayer"
          eType="#//architecture/InfrastructureLayer" eOpposite="#//architecture/InfrastructureLayer/services"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PlatformService" abstract="true" eSuperTypes="#//architecture/Service">
      <eStructuralFeatures xsi:type="ecore:EReference" name="platformLayer" eType="#//architecture/PlatformLayer"
          eOpposite="#//architecture/PlatformLayer/services"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareService" abstract="true" eSuperTypes="#//architecture/Service #//architecture/OperationInterfaceContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="softwareLayer" eType="#//architecture/SoftwareLayer"
          eOpposite="#//architecture/SoftwareLayer/services"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeployablePlatformService" abstract="true"
        eSuperTypes="#//architecture/PlatformService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="computingInfrastructureService"
          eType="#//architecture/ComputingInfrastructureService" eOpposite="#//architecture/ComputingInfrastructureService/platformServices"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
          eType="#//definition/DeployablePlatformServiceDescriptor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalPlatformService" abstract="true"
        eSuperTypes="#//architecture/PlatformService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
          eType="#//definition/ExternalPlatformServiceDescriptor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeployableRuntimeService" eSuperTypes="#//architecture/DeployablePlatformService #//architecture/SoftwareServiceContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeployableSupportService" eSuperTypes="#//architecture/DeployablePlatformService #//architecture/OperationInterfaceContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalRuntimeService" eSuperTypes="#//architecture/ExternalPlatformService #//architecture/SoftwareServiceContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalSupportService" eSuperTypes="#//architecture/ExternalPlatformService #//architecture/OperationInterfaceContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalSoftwareService" eSuperTypes="#//architecture/SoftwareService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceProxy" lowerBound="1"
          eType="#//architecture/ServiceProxy" eOpposite="#//architecture/ServiceProxy/softwareService"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeployableSoftwareService" eSuperTypes="#//architecture/SoftwareService">
      <eStructuralFeatures xsi:type="ecore:EReference" name="runtimePlatformService"
          eType="#//architecture/SoftwareServiceContainer" eOpposite="#//architecture/SoftwareServiceContainer/softwareServices"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputingInfrastructureService" eSuperTypes="#//architecture/InfrastructureService">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Instance model represents an IaaS computing node; virtual machine in the elastic cloud environment. The node components (see Node) can be deployed/installed on instances.&#xA;The behaviour and hardware are specified through instance descriptors (see InstanceDescriptor), which are specified in cloud provider descriptor; each IaaS cloud environment has a set of predefined computing nodes that can be used. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" eType="#//definition/ComputingInfrastructureServiceDescriptor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platformServices" upperBound="-1"
          eType="#//architecture/DeployablePlatformService" eOpposite="#//architecture/DeployablePlatformService/computingInfrastructureService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareServiceContainer" abstract="true"
        interface="true" eSuperTypes="#//core/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="softwareServices" upperBound="-1"
          eType="#//architecture/DeployableSoftwareService" eOpposite="#//architecture/DeployableSoftwareService/runtimePlatformService"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationInterfaceContainer" abstract="true"
        interface="true" eSuperTypes="#//core/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" upperBound="-1"
          eType="#//core/OperationInterface" containment="true" eOpposite="#//core/OperationInterface/providingContainer">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
          eType="#//core/OperationInterface" eOpposite="#//core/OperationInterface/requiringContainer">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Connection represents dependency between two components or between connector and component. The performance of the connection (e.g. bandwidth and latency) is defined through connection descriptors. "/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalConnection" eSuperTypes="#//architecture/Connection">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The InternalConnection represents dependency between two components from the same cloud environment (i.e. CloudProvider). &#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePlatformService"
          lowerBound="1" eType="#//architecture/PlatformService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destinationPlatformService"
          lowerBound="1" eType="#//architecture/PlatformService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HybridConnection" eSuperTypes="#//architecture/Connection">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The HybridConnection represents dependency between two components from different cloud environments (i.e. CloudProvider). This connection enables modeling of hybrid clouds.&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePlatformService"
          lowerBound="1" eType="#//architecture/PlatformService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetPlatformService"
          lowerBound="1" eType="#//architecture/PlatformService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
          eType="#//definition/NetworkInfrastructureServiceDescriptor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalConnection" eSuperTypes="#//architecture/Connection">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ExternalConnection represents the dependency between component and connector (see Connector) and therefore the connection that links outside environment with the modelled system.&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="proxy" eType="#//architecture/Proxy">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platformService" eType="#//architecture/PlatformService">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOutbound" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
          eType="#//definition/NetworkInfrastructureServiceDescriptor">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Proxy" abstract="true" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Connector model represents external environment to which the system provides (usage connectors) its services or from which it requires services (service connector). Link between connectors and the system components is created through external connections (see ExternalConnection)."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceProxy" eSuperTypes="#//architecture/Proxy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ServiceConnector represents external services (SaaS) that are used by the modelled system. It exposes interfaces (i.e. OperationInterface), which are required by the modules contained in the system components. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="softwareService" eType="#//architecture/ExternalSoftwareService"
          containment="true" eOpposite="#//architecture/ExternalSoftwareService/serviceProxy"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UsageProxy" eSuperTypes="#//architecture/Proxy #//architecture/OperationInterfaceContainer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The UsageConnector model contains the interfaces that are exposed by the system. Each component connected to usage connector  (through external connection) can expose interfaces defined in their modules to an external environment."/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="definition" nsURI="http://eu.cloudscaleproject.env/CloudscaleComponentModel/Definition/1.0"
      nsPrefix="definition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This package defines the descriptors, which are referenced by classes in Architecture package, and provides exact specification to cloud system components. Additionally package defines also two definition classes (i.e. CloudDefinition and SoftwareDefinition) that are used as descriptor containers, whose purpose is to extend available specifications.&#xA;"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Definition" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=""/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemDefinition" eSuperTypes="#//definition/Definition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The SystemDefinition is part of the CSM and is container for all descriptors referenced by the architecture classes. The main purpose of a such container is to be able to reference same descriptor more than once, and thus providing easier maintenance of a system specifications in the case of change (e.g. AWS upgrades it’s instances - more memory and storage)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" upperBound="-1"
          eType="#//definition/Descriptor" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloudDefinition" eSuperTypes="#//definition/Definition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The CloudDefinition model specifies all the details of the cloud provider (see CloudProvider). It consists of cloud provider descriptor, instance descriptors (in case the IaaS clouds), service descriptors (in case of PaaS clouds) and connection descriptors, specifying internal connections (e.g. bandwidth and latency). &#xA;This model is not meant to be included into CSM model, but it provides ability for specifying different cloud environments, which descriptors can be assigned to CSM model entities."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptor" lowerBound="1"
          eType="#//definition/CloudEnvironmentDescriptor" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructureDescriptors"
          upperBound="-1" eType="#//definition/InfrastructureServiceDescriptor" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="platformDescriptors"
          upperBound="-1" eType="#//definition/ExternalPlatformServiceDescriptor"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareDefinition" eSuperTypes="#//definition/Definition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The SoftwareDefinition model specifies the deployable 3rd party software that can be used to specify node components (see Node) or used operating systems on the instances (see Instance).&#xA;This model is not meant to be included into CSM model, but it provides ability for specifying different software bundles, which descriptors can be assigned to CSM model entities.&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deployablePlatformServiceDescriptors"
          upperBound="-1" eType="#//definition/DeployablePlatformServiceDescriptor"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Descriptor" eSuperTypes="#//core/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Descriptor model is used to specify the behaviour of the CSM architecture elements (e.g. components, connectors, cloud providers, …). For the descriptors that are available in the specific cloud provider, the provider id is defined (e.g. specification of services provided by specific PaaS provider). "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloudEnvironmentDescriptor" eSuperTypes="#//definition/Descriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The CloudProviderDecscriptor specifies the global properties of the cloud providers (see CloudProvider). &#xA;In the current version only Entity properties are available; name and description."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="availabilityZones" upperBound="-1"
          eType="#//definition/AvailabilityZoneDescriptor" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
          eType="#//definition/RegionDescriptor" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RegionDescriptor" eSuperTypes="#//definition/Descriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The RegionDescriptro specify the properties of the cloud regions (see CloudProvider). &#xA;In the current version only Entity properties are available; name and description."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AvailabilityZoneDescriptor" eSuperTypes="#//definition/Descriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The AvaliabilityZoneDescriptor specify the properties of the cloud availability zones (see CloudProvider). &#xA;In the current version only Entity properties are available; name and description."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalConnectionDescriptor"
          lowerBound="1" eType="#//definition/NetworkInfrastructureServiceDescriptor"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InfrastructureServiceDescriptor" eSuperTypes="#//definition/Descriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ServiceDescriptor specify properties of PaaS services. &#xA;In the current version only entity properties are available; name and description.&#xA;"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkInfrastructureServiceDescriptor"
        eSuperTypes="#//definition/InfrastructureServiceDescriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ConnectionDescriptor specifies properties of the connections. &#xA;In the current version following properties are defined: bandwidth and latency. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="latency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputingInfrastructureServiceDescriptor"
        eSuperTypes="#//definition/InfrastructureServiceDescriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The InstanceDescriptor specify hardware properties of the instances in IaaS cloud environment.  Currently following properties are defined: cpu, cpuUnits, memory and storage. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuUnits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="storage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeployablePlatformServiceDescriptor"
        abstract="true" interface="true" eSuperTypes="#//definition/Descriptor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The OsDescriptor specify the operating system installed on the IaaS instances (see Instance).&#xA;In the current version only entity properties are available; name and description."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalPlatformServiceDescriptor"
        abstract="true" interface="true" eSuperTypes="#//definition/Descriptor"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeployableRuntimeServiceDescriptor"
        eSuperTypes="#//definition/DeployablePlatformServiceDescriptor"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalRuntimeServiceDescriptor"
        eSuperTypes="#//definition/ExternalPlatformServiceDescriptor"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeployableSupportServiceDescriptor"
        eSuperTypes="#//definition/DeployablePlatformServiceDescriptor"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalSupportServiceDescriptor"
        eSuperTypes="#//definition/ExternalPlatformServiceDescriptor"/>
  </eSubpackages>
</ecore:EPackage>
